# Generated by Django 4.2.10 on 2024-04-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='stret_address',
            new_name='street_address',
        ),
    ]
